apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: storage
  labels:
    component: elasticsearch
    role: data
spec:
  type: ClusterIP
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: transport
    port: 9300
    protocol: TCP