apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
  labels:
    k8s-app: kibana
data:
  kibana.yml: |
    elasticsearch.url: "http://elasticsearch-client.storage:9200"
    server.host: "0.0.0.0"
    server.basePath: /kibana