apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ba-payment-processor-dispatcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ba-payment-processor-dispatcher
  template:
    metadata:
      labels:
        app: ba-payment-processor-dispatcher
    spec:
      containers:
        - name: ba-payment-processor-dispatcher
          image: maxkondr/ba-payment-processor-dispatcher
          ports:
          - name: grpc
            containerPort: 7770
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
