apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: porta-node-exporter
  name: porta-node-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9101
    targetPort: http
  selector:
    app: porta-node-exporter
